/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, EClass, BasicEObject, EStructuralFeature } from '@emfts/core';
import type { FeatureOverride } from './FeatureOverride.js';

/**
 * ClassOverride
 * @generated
 */
export interface ClassOverride extends EObject {
  ecoreClass: EClass;
  generateInterface?: boolean;
  generateImpl?: boolean;
  extendsClass?: string;
  implementsInterfaces: EList<string>;
  featureOverrides: EList<FeatureOverride>;

}
