/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * ClassDefaults
 * @generated
 */
export interface ClassDefaults extends EObject {
  generateInterface?: boolean;
  generateImpl?: boolean;
  rootExtendsClass?: string;
  rootExtendsInterface?: string;

}
