/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList, createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { FeatureOverride } from './FeatureOverride.js';
import type { ClassOverride } from './ClassOverride.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of ClassOverride
 * @generated
 */
export class ClassOverrideImpl extends BasicEObject implements ClassOverride {
  // Feature ID Constants (eLiterals)
  static readonly ECORE_CLASS: number = 0;
  static readonly GENERATE_INTERFACE: number = 1;
  static readonly GENERATE_IMPL: number = 2;
  static readonly EXTENDS_CLASS: number = 3;
  static readonly IMPLEMENTS_INTERFACES: number = 4;
  static readonly FEATURE_OVERRIDES: number = 5;

  // Private fields
  private _ecoreClass?: EClass;
  private _generateInterface?: boolean;
  private _generateImpl?: boolean;
  private _extendsClass?: string;
  private _implementsInterfaces!: EList<string>;
  private _featureOverrides!: EList<FeatureOverride>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.CLASS_OVERRIDE;
  }

  // Getters and Setters
  get ecoreClass(): EClass {
    return this._ecoreClass!;
  }

  set ecoreClass(value: EClass) {
    const oldValue = this._ecoreClass;
    this._ecoreClass = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassOverrideImpl.ECORE_CLASS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassOverrideImpl.ECORE_CLASS,
        merge: () => false
      });
    }
  }

  get generateInterface(): boolean {
    return this._generateInterface!;
  }

  set generateInterface(value: boolean) {
    const oldValue = this._generateInterface;
    this._generateInterface = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassOverrideImpl.GENERATE_INTERFACE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassOverrideImpl.GENERATE_INTERFACE,
        merge: () => false
      });
    }
  }

  get generateImpl(): boolean {
    return this._generateImpl!;
  }

  set generateImpl(value: boolean) {
    const oldValue = this._generateImpl;
    this._generateImpl = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassOverrideImpl.GENERATE_IMPL),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassOverrideImpl.GENERATE_IMPL,
        merge: () => false
      });
    }
  }

  get extendsClass(): string {
    return this._extendsClass!;
  }

  set extendsClass(value: string) {
    const oldValue = this._extendsClass;
    this._extendsClass = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassOverrideImpl.EXTENDS_CLASS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassOverrideImpl.EXTENDS_CLASS,
        merge: () => false
      });
    }
  }

  get implementsInterfaces(): EList<string> {
    if (!this._implementsInterfaces) {
      this._implementsInterfaces = createBasicEList<any>(this, this.eClass().getEStructuralFeature('implementsInterfaces')!);
    }
    return this._implementsInterfaces;
  }

  get featureOverrides(): EList<FeatureOverride> {
    if (!this._featureOverrides) {
      this._featureOverrides = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('featureOverrides') as EReference);
    }
    return this._featureOverrides;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassOverrideImpl.ECORE_CLASS:
        return this.ecoreClass;
      case ClassOverrideImpl.GENERATE_INTERFACE:
        return this.generateInterface;
      case ClassOverrideImpl.GENERATE_IMPL:
        return this.generateImpl;
      case ClassOverrideImpl.EXTENDS_CLASS:
        return this.extendsClass;
      case ClassOverrideImpl.IMPLEMENTS_INTERFACES:
        return this.implementsInterfaces;
      case ClassOverrideImpl.FEATURE_OVERRIDES:
        return this.featureOverrides;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassOverrideImpl.ECORE_CLASS:
        this.ecoreClass = newValue as EClass;
        super.eSet(feature, newValue);
        break;
      case ClassOverrideImpl.GENERATE_INTERFACE:
        this.generateInterface = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case ClassOverrideImpl.GENERATE_IMPL:
        this.generateImpl = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case ClassOverrideImpl.EXTENDS_CLASS:
        this.extendsClass = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ClassOverrideImpl.IMPLEMENTS_INTERFACES:
        this.implementsInterfaces.clear();
        this.implementsInterfaces.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ClassOverrideImpl.FEATURE_OVERRIDES:
        this.featureOverrides.clear();
        this.featureOverrides.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassOverrideImpl.ECORE_CLASS:
        return this._ecoreClass !== undefined;
      case ClassOverrideImpl.GENERATE_INTERFACE:
        return this._generateInterface !== undefined;
      case ClassOverrideImpl.GENERATE_IMPL:
        return this._generateImpl !== undefined;
      case ClassOverrideImpl.EXTENDS_CLASS:
        return this._extendsClass !== undefined;
      case ClassOverrideImpl.IMPLEMENTS_INTERFACES:
        return this._implementsInterfaces !== undefined && !this._implementsInterfaces.isEmpty();
      case ClassOverrideImpl.FEATURE_OVERRIDES:
        return this._featureOverrides !== undefined && !this._featureOverrides.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassOverrideImpl.ECORE_CLASS:
        this._ecoreClass = undefined;
        return;
      case ClassOverrideImpl.GENERATE_INTERFACE:
        this._generateInterface = undefined;
        return;
      case ClassOverrideImpl.GENERATE_IMPL:
        this._generateImpl = undefined;
        return;
      case ClassOverrideImpl.EXTENDS_CLASS:
        this._extendsClass = undefined;
        return;
      case ClassOverrideImpl.IMPLEMENTS_INTERFACES:
        if (this._implementsInterfaces) this._implementsInterfaces.clear();
        return;
      case ClassOverrideImpl.FEATURE_OVERRIDES:
        if (this._featureOverrides) this._featureOverrides.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
