/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ClassDefaults } from './ClassDefaults.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of ClassDefaults
 * @generated
 */
export class ClassDefaultsImpl extends BasicEObject implements ClassDefaults {
  // Feature ID Constants (eLiterals)
  static readonly GENERATE_INTERFACE: number = 0;
  static readonly GENERATE_IMPL: number = 1;
  static readonly ROOT_EXTENDS_CLASS: number = 2;
  static readonly ROOT_EXTENDS_INTERFACE: number = 3;

  // Private fields
  private _generateInterface?: unknown;
  private _generateImpl?: unknown;
  private _rootExtendsClass?: unknown;
  private _rootExtendsInterface?: unknown;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.CLASS_DEFAULTS;
  }

  // Getters and Setters
  get generateInterface(): unknown {
    return this._generateInterface!;
  }

  set generateInterface(value: unknown) {
    const oldValue = this._generateInterface;
    this._generateInterface = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassDefaultsImpl.GENERATE_INTERFACE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassDefaultsImpl.GENERATE_INTERFACE,
        merge: () => false
      });
    }
  }

  get generateImpl(): unknown {
    return this._generateImpl!;
  }

  set generateImpl(value: unknown) {
    const oldValue = this._generateImpl;
    this._generateImpl = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassDefaultsImpl.GENERATE_IMPL),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassDefaultsImpl.GENERATE_IMPL,
        merge: () => false
      });
    }
  }

  get rootExtendsClass(): unknown {
    return this._rootExtendsClass!;
  }

  set rootExtendsClass(value: unknown) {
    const oldValue = this._rootExtendsClass;
    this._rootExtendsClass = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassDefaultsImpl.ROOT_EXTENDS_CLASS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassDefaultsImpl.ROOT_EXTENDS_CLASS,
        merge: () => false
      });
    }
  }

  get rootExtendsInterface(): unknown {
    return this._rootExtendsInterface!;
  }

  set rootExtendsInterface(value: unknown) {
    const oldValue = this._rootExtendsInterface;
    this._rootExtendsInterface = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ClassDefaultsImpl.ROOT_EXTENDS_INTERFACE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ClassDefaultsImpl.ROOT_EXTENDS_INTERFACE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassDefaultsImpl.GENERATE_INTERFACE:
        return this.generateInterface;
      case ClassDefaultsImpl.GENERATE_IMPL:
        return this.generateImpl;
      case ClassDefaultsImpl.ROOT_EXTENDS_CLASS:
        return this.rootExtendsClass;
      case ClassDefaultsImpl.ROOT_EXTENDS_INTERFACE:
        return this.rootExtendsInterface;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassDefaultsImpl.GENERATE_INTERFACE:
        this.generateInterface = newValue as unknown;
        super.eSet(feature, newValue);
        break;
      case ClassDefaultsImpl.GENERATE_IMPL:
        this.generateImpl = newValue as unknown;
        super.eSet(feature, newValue);
        break;
      case ClassDefaultsImpl.ROOT_EXTENDS_CLASS:
        this.rootExtendsClass = newValue as unknown;
        super.eSet(feature, newValue);
        break;
      case ClassDefaultsImpl.ROOT_EXTENDS_INTERFACE:
        this.rootExtendsInterface = newValue as unknown;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassDefaultsImpl.GENERATE_INTERFACE:
        return this._generateInterface !== undefined;
      case ClassDefaultsImpl.GENERATE_IMPL:
        return this._generateImpl !== undefined;
      case ClassDefaultsImpl.ROOT_EXTENDS_CLASS:
        return this._rootExtendsClass !== undefined;
      case ClassDefaultsImpl.ROOT_EXTENDS_INTERFACE:
        return this._rootExtendsInterface !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ClassDefaultsImpl.GENERATE_INTERFACE:
        this._generateInterface = undefined;
        return;
      case ClassDefaultsImpl.GENERATE_IMPL:
        this._generateImpl = undefined;
        return;
      case ClassDefaultsImpl.ROOT_EXTENDS_CLASS:
        this._rootExtendsClass = undefined;
        return;
      case ClassDefaultsImpl.ROOT_EXTENDS_INTERFACE:
        this._rootExtendsInterface = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
