/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EStructuralFeature, BasicEObject, EClass } from '@emfts/core';

/**
 * FeatureOverride
 * @generated
 */
export interface FeatureOverride extends EObject {
  ecoreFeature: EStructuralFeature;
  notify?: unknown;
  property?: unknown;
  customGetter?: unknown;
  customSetter?: unknown;

}
