/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EStructuralFeature, BasicEObject, EClass } from '@emfts/core';
import type { PropertyMode } from './PropertyMode.js';

/**
 * FeatureOverride
 * @generated
 */
export interface FeatureOverride extends EObject {
  ecoreFeature: EStructuralFeature;
  notify?: boolean;
  property?: PropertyMode;
  customGetter?: string;
  customSetter?: string;

}
