/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import { PropertyMode } from './PropertyMode.js';
import type { FeatureDefaults } from './FeatureDefaults.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of FeatureDefaults
 * @generated
 */
export class FeatureDefaultsImpl extends BasicEObject implements FeatureDefaults {
  // Feature ID Constants (eLiterals)
  static readonly NOTIFY: number = 0;
  static readonly PROPERTY: number = 1;

  // Private fields
  private _notify: boolean = true;
  private _property: PropertyMode = PropertyMode.editable;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.FEATURE_DEFAULTS;
  }

  // Getters and Setters
  get notify(): boolean {
    return this._notify!;
  }

  set notify(value: boolean) {
    const oldValue = this._notify;
    this._notify = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureDefaultsImpl.NOTIFY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureDefaultsImpl.NOTIFY,
        merge: () => false
      });
    }
  }

  get property(): PropertyMode {
    return this._property!;
  }

  set property(value: PropertyMode) {
    const oldValue = this._property;
    this._property = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureDefaultsImpl.PROPERTY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureDefaultsImpl.PROPERTY,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureDefaultsImpl.NOTIFY:
        return this.notify;
      case FeatureDefaultsImpl.PROPERTY:
        return this.property;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureDefaultsImpl.NOTIFY:
        this.notify = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case FeatureDefaultsImpl.PROPERTY:
        this.property = newValue as PropertyMode;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureDefaultsImpl.NOTIFY:
        return this._notify !== true;
      case FeatureDefaultsImpl.PROPERTY:
        return this._property !== PropertyMode.editable;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureDefaultsImpl.NOTIFY:
        this._notify = true;
        return;
      case FeatureDefaultsImpl.PROPERTY:
        this._property = PropertyMode.editable;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
