/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import { PropertyMode } from './PropertyMode.js';
import type { FeatureOverride } from './FeatureOverride.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of FeatureOverride
 * @generated
 */
export class FeatureOverrideImpl extends BasicEObject implements FeatureOverride {
  // Feature ID Constants (eLiterals)
  static readonly ECORE_FEATURE: number = 0;
  static readonly NOTIFY: number = 1;
  static readonly PROPERTY: number = 2;
  static readonly CUSTOM_GETTER: number = 3;
  static readonly CUSTOM_SETTER: number = 4;

  // Private fields
  private _ecoreFeature?: EStructuralFeature;
  private _notify?: boolean;
  private _property: PropertyMode = PropertyMode.editable;
  private _customGetter?: string;
  private _customSetter?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.FEATURE_OVERRIDE;
  }

  // Getters and Setters
  get ecoreFeature(): EStructuralFeature {
    return this._ecoreFeature!;
  }

  set ecoreFeature(value: EStructuralFeature) {
    const oldValue = this._ecoreFeature;
    this._ecoreFeature = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureOverrideImpl.ECORE_FEATURE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureOverrideImpl.ECORE_FEATURE,
        merge: () => false
      });
    }
  }

  get notify(): boolean {
    return this._notify!;
  }

  set notify(value: boolean) {
    const oldValue = this._notify;
    this._notify = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureOverrideImpl.NOTIFY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureOverrideImpl.NOTIFY,
        merge: () => false
      });
    }
  }

  get property(): PropertyMode {
    return this._property!;
  }

  set property(value: PropertyMode) {
    const oldValue = this._property;
    this._property = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureOverrideImpl.PROPERTY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureOverrideImpl.PROPERTY,
        merge: () => false
      });
    }
  }

  get customGetter(): string {
    return this._customGetter!;
  }

  set customGetter(value: string) {
    const oldValue = this._customGetter;
    this._customGetter = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureOverrideImpl.CUSTOM_GETTER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureOverrideImpl.CUSTOM_GETTER,
        merge: () => false
      });
    }
  }

  get customSetter(): string {
    return this._customSetter!;
  }

  set customSetter(value: string) {
    const oldValue = this._customSetter;
    this._customSetter = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(FeatureOverrideImpl.CUSTOM_SETTER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => FeatureOverrideImpl.CUSTOM_SETTER,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureOverrideImpl.ECORE_FEATURE:
        return this.ecoreFeature;
      case FeatureOverrideImpl.NOTIFY:
        return this.notify;
      case FeatureOverrideImpl.PROPERTY:
        return this.property;
      case FeatureOverrideImpl.CUSTOM_GETTER:
        return this.customGetter;
      case FeatureOverrideImpl.CUSTOM_SETTER:
        return this.customSetter;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureOverrideImpl.ECORE_FEATURE:
        this.ecoreFeature = newValue as EStructuralFeature;
        super.eSet(feature, newValue);
        break;
      case FeatureOverrideImpl.NOTIFY:
        this.notify = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case FeatureOverrideImpl.PROPERTY:
        this.property = newValue as PropertyMode;
        super.eSet(feature, newValue);
        break;
      case FeatureOverrideImpl.CUSTOM_GETTER:
        this.customGetter = newValue as string;
        super.eSet(feature, newValue);
        break;
      case FeatureOverrideImpl.CUSTOM_SETTER:
        this.customSetter = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureOverrideImpl.ECORE_FEATURE:
        return this._ecoreFeature !== undefined;
      case FeatureOverrideImpl.NOTIFY:
        return this._notify !== undefined;
      case FeatureOverrideImpl.PROPERTY:
        return this._property !== PropertyMode.editable;
      case FeatureOverrideImpl.CUSTOM_GETTER:
        return this._customGetter !== undefined;
      case FeatureOverrideImpl.CUSTOM_SETTER:
        return this._customSetter !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case FeatureOverrideImpl.ECORE_FEATURE:
        this._ecoreFeature = undefined;
        return;
      case FeatureOverrideImpl.NOTIFY:
        this._notify = undefined;
        return;
      case FeatureOverrideImpl.PROPERTY:
        this._property = PropertyMode.editable;
        return;
      case FeatureOverrideImpl.CUSTOM_GETTER:
        this._customGetter = undefined;
        return;
      case FeatureOverrideImpl.CUSTOM_SETTER:
        this._customSetter = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
