/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { PropertyMode } from './PropertyMode.js';

/**
 * FeatureDefaults
 * @generated
 */
export interface FeatureDefaults extends EObject {
  notify?: boolean;
  property?: PropertyMode;

}
