/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEPackage, BasicEClass, BasicEAttribute, BasicEReference, getEcorePackage } from '@emfts/core';
import type { EClass, EAttribute, EReference, EEnum } from '@emfts/core';
import { GenConfigFactory } from './GenConfigFactory.js';

/**
 * GenConfig Package
 * @generated
 */
export class GenConfigPackage extends BasicEPackage {
  static readonly eNAME = 'genconfig';
  static readonly eNS_URI = 'http://www.emfts.org/genconfig/1.0';
  static readonly eNS_PREFIX = 'genconfig';

  // Singleton instance
  private static _instance: GenConfigPackage;

  static get eINSTANCE(): GenConfigPackage {
    if (!this._instance) {
      this._instance = new GenConfigPackage();
      this._instance.init();
    }
    return this._instance;
  }

  /**
   * Literals for quick access to metaclasses and features
   */
  static readonly Literals = {
    GEN_CONFIG: null as unknown as EClass,
    GEN_CONFIG__ECORE_PACKAGE: null as unknown as EAttribute | EReference,
    GEN_CONFIG__GENERATION: null as unknown as EAttribute | EReference,
    GEN_CONFIG__PACKAGE: null as unknown as EAttribute | EReference,
    GEN_CONFIG__CLASS_DEFAULTS: null as unknown as EAttribute | EReference,
    GEN_CONFIG__FEATURE_DEFAULTS: null as unknown as EAttribute | EReference,
    GEN_CONFIG__CLASS_OVERRIDES: null as unknown as EAttribute | EReference,
    GEN_CONFIG__REFERENCED_PACKAGES: null as unknown as EAttribute | EReference,
    REFERENCED_PACKAGE: null as unknown as EClass,
    REFERENCED_PACKAGE__NS_U_R_I: null as unknown as EAttribute | EReference,
    REFERENCED_PACKAGE__IMPORT_PATH: null as unknown as EAttribute | EReference,
    GENERATION_SETTINGS: null as unknown as EClass,
    GENERATION_SETTINGS__MODE: null as unknown as EAttribute | EReference,
    GENERATION_SETTINGS__OUTPUT_DIR: null as unknown as EAttribute | EReference,
    GENERATION_SETTINGS__FILE_EXTENSION: null as unknown as EAttribute | EReference,
    GENERATION_SETTINGS__HEADER_COMMENT: null as unknown as EAttribute | EReference,
    GENERATION_SETTINGS__ANNOTATIONS_PACKAGE: null as unknown as EAttribute | EReference,
    PACKAGE_SETTINGS: null as unknown as EClass,
    PACKAGE_SETTINGS__PREFIX: null as unknown as EAttribute | EReference,
    PACKAGE_SETTINGS__BASE_PACKAGE: null as unknown as EAttribute | EReference,
    PACKAGE_SETTINGS__GENERATE_FACTORY: null as unknown as EAttribute | EReference,
    PACKAGE_SETTINGS__GENERATE_PACKAGE: null as unknown as EAttribute | EReference,
    PACKAGE_SETTINGS__GENERATE_INDEX: null as unknown as EAttribute | EReference,
    CLASS_DEFAULTS: null as unknown as EClass,
    CLASS_DEFAULTS__GENERATE_INTERFACE: null as unknown as EAttribute | EReference,
    CLASS_DEFAULTS__GENERATE_IMPL: null as unknown as EAttribute | EReference,
    CLASS_DEFAULTS__ROOT_EXTENDS_CLASS: null as unknown as EAttribute | EReference,
    CLASS_DEFAULTS__ROOT_EXTENDS_INTERFACE: null as unknown as EAttribute | EReference,
    FEATURE_DEFAULTS: null as unknown as EClass,
    FEATURE_DEFAULTS__NOTIFY: null as unknown as EAttribute | EReference,
    FEATURE_DEFAULTS__PROPERTY: null as unknown as EAttribute | EReference,
    CLASS_OVERRIDE: null as unknown as EClass,
    CLASS_OVERRIDE__ECORE_CLASS: null as unknown as EAttribute | EReference,
    CLASS_OVERRIDE__GENERATE_INTERFACE: null as unknown as EAttribute | EReference,
    CLASS_OVERRIDE__GENERATE_IMPL: null as unknown as EAttribute | EReference,
    CLASS_OVERRIDE__EXTENDS_CLASS: null as unknown as EAttribute | EReference,
    CLASS_OVERRIDE__IMPLEMENTS_INTERFACES: null as unknown as EAttribute | EReference,
    CLASS_OVERRIDE__FEATURE_OVERRIDES: null as unknown as EAttribute | EReference,
    FEATURE_OVERRIDE: null as unknown as EClass,
    FEATURE_OVERRIDE__ECORE_FEATURE: null as unknown as EAttribute | EReference,
    FEATURE_OVERRIDE__NOTIFY: null as unknown as EAttribute | EReference,
    FEATURE_OVERRIDE__PROPERTY: null as unknown as EAttribute | EReference,
    FEATURE_OVERRIDE__CUSTOM_GETTER: null as unknown as EAttribute | EReference,
    FEATURE_OVERRIDE__CUSTOM_SETTER: null as unknown as EAttribute | EReference,
  };

  private constructor() {
    super();
    this.setName(GenConfigPackage.eNAME);
    this.setNsURI(GenConfigPackage.eNS_URI);
    this.setNsPrefix(GenConfigPackage.eNS_PREFIX);
  }

  /**
   * Initialize package contents
   */
  private init(): void {
    // Wire the generated factory so loaded/created instances are typed Impls.
    // eINSTANCE is already assigned at this point, so the factory's back
    // reference to the package resolves without re-entering init()
    this.setEFactoryInstance(GenConfigFactory.eINSTANCE);

    // Create GenConfig class
    const genConfigClass = new BasicEClass();
    genConfigClass.setName('GenConfig');
    genConfigClass.setAbstract(false);
    genConfigClass.setInterface(false);
    this.getEClassifiers().push(genConfigClass);
    genConfigClass.setEPackage(this);
    GenConfigPackage.Literals.GEN_CONFIG = genConfigClass;

    // Create ecorePackage feature
    const genConfig_ecorePackage = new BasicEReference();
    genConfig_ecorePackage.setContainment(false);
    genConfig_ecorePackage.setName('ecorePackage');
    genConfig_ecorePackage.setLowerBound(1);
    genConfig_ecorePackage.setUpperBound(1);
    genConfigClass.getEStructuralFeatures().push(genConfig_ecorePackage);
    GenConfigPackage.Literals.GEN_CONFIG__ECORE_PACKAGE = genConfig_ecorePackage;

    // Create generation feature
    const genConfig_generation = new BasicEReference();
    genConfig_generation.setContainment(true);
    genConfig_generation.setName('generation');
    genConfig_generation.setLowerBound(1);
    genConfig_generation.setUpperBound(1);
    genConfigClass.getEStructuralFeatures().push(genConfig_generation);
    GenConfigPackage.Literals.GEN_CONFIG__GENERATION = genConfig_generation;

    // Create package feature
    const genConfig_package = new BasicEReference();
    genConfig_package.setContainment(true);
    genConfig_package.setName('package');
    genConfig_package.setLowerBound(1);
    genConfig_package.setUpperBound(1);
    genConfigClass.getEStructuralFeatures().push(genConfig_package);
    GenConfigPackage.Literals.GEN_CONFIG__PACKAGE = genConfig_package;

    // Create classDefaults feature
    const genConfig_classDefaults = new BasicEReference();
    genConfig_classDefaults.setContainment(true);
    genConfig_classDefaults.setName('classDefaults');
    genConfig_classDefaults.setLowerBound(0);
    genConfig_classDefaults.setUpperBound(1);
    genConfigClass.getEStructuralFeatures().push(genConfig_classDefaults);
    GenConfigPackage.Literals.GEN_CONFIG__CLASS_DEFAULTS = genConfig_classDefaults;

    // Create featureDefaults feature
    const genConfig_featureDefaults = new BasicEReference();
    genConfig_featureDefaults.setContainment(true);
    genConfig_featureDefaults.setName('featureDefaults');
    genConfig_featureDefaults.setLowerBound(0);
    genConfig_featureDefaults.setUpperBound(1);
    genConfigClass.getEStructuralFeatures().push(genConfig_featureDefaults);
    GenConfigPackage.Literals.GEN_CONFIG__FEATURE_DEFAULTS = genConfig_featureDefaults;

    // Create classOverrides feature
    const genConfig_classOverrides = new BasicEReference();
    genConfig_classOverrides.setContainment(true);
    genConfig_classOverrides.setName('classOverrides');
    genConfig_classOverrides.setLowerBound(0);
    genConfig_classOverrides.setUpperBound(-1);
    genConfigClass.getEStructuralFeatures().push(genConfig_classOverrides);
    GenConfigPackage.Literals.GEN_CONFIG__CLASS_OVERRIDES = genConfig_classOverrides;

    // Create referencedPackages feature
    const genConfig_referencedPackages = new BasicEReference();
    genConfig_referencedPackages.setContainment(true);
    genConfig_referencedPackages.setName('referencedPackages');
    genConfig_referencedPackages.setLowerBound(0);
    genConfig_referencedPackages.setUpperBound(-1);
    genConfigClass.getEStructuralFeatures().push(genConfig_referencedPackages);
    GenConfigPackage.Literals.GEN_CONFIG__REFERENCED_PACKAGES = genConfig_referencedPackages;

    // Create ReferencedPackage class
    const referencedPackageClass = new BasicEClass();
    referencedPackageClass.setName('ReferencedPackage');
    referencedPackageClass.setAbstract(false);
    referencedPackageClass.setInterface(false);
    this.getEClassifiers().push(referencedPackageClass);
    referencedPackageClass.setEPackage(this);
    GenConfigPackage.Literals.REFERENCED_PACKAGE = referencedPackageClass;

    // Create nsURI feature
    const referencedPackage_nsURI = new BasicEAttribute();
    referencedPackage_nsURI.setName('nsURI');
    referencedPackage_nsURI.setLowerBound(1);
    referencedPackage_nsURI.setUpperBound(1);
    referencedPackageClass.getEStructuralFeatures().push(referencedPackage_nsURI);
    GenConfigPackage.Literals.REFERENCED_PACKAGE__NS_U_R_I = referencedPackage_nsURI;

    // Create importPath feature
    const referencedPackage_importPath = new BasicEAttribute();
    referencedPackage_importPath.setName('importPath');
    referencedPackage_importPath.setLowerBound(1);
    referencedPackage_importPath.setUpperBound(1);
    referencedPackageClass.getEStructuralFeatures().push(referencedPackage_importPath);
    GenConfigPackage.Literals.REFERENCED_PACKAGE__IMPORT_PATH = referencedPackage_importPath;

    // Create GenerationSettings class
    const generationSettingsClass = new BasicEClass();
    generationSettingsClass.setName('GenerationSettings');
    generationSettingsClass.setAbstract(false);
    generationSettingsClass.setInterface(false);
    this.getEClassifiers().push(generationSettingsClass);
    generationSettingsClass.setEPackage(this);
    GenConfigPackage.Literals.GENERATION_SETTINGS = generationSettingsClass;

    // Create mode feature
    const generationSettings_mode = new BasicEAttribute();
    generationSettings_mode.setName('mode');
    generationSettings_mode.setLowerBound(1);
    generationSettings_mode.setUpperBound(1);
    generationSettingsClass.getEStructuralFeatures().push(generationSettings_mode);
    GenConfigPackage.Literals.GENERATION_SETTINGS__MODE = generationSettings_mode;

    // Create outputDir feature
    const generationSettings_outputDir = new BasicEAttribute();
    generationSettings_outputDir.setName('outputDir');
    generationSettings_outputDir.setLowerBound(1);
    generationSettings_outputDir.setUpperBound(1);
    generationSettingsClass.getEStructuralFeatures().push(generationSettings_outputDir);
    GenConfigPackage.Literals.GENERATION_SETTINGS__OUTPUT_DIR = generationSettings_outputDir;

    // Create fileExtension feature
    const generationSettings_fileExtension = new BasicEAttribute();
    generationSettings_fileExtension.setName('fileExtension');
    generationSettings_fileExtension.setLowerBound(0);
    generationSettings_fileExtension.setUpperBound(1);
    generationSettingsClass.getEStructuralFeatures().push(generationSettings_fileExtension);
    GenConfigPackage.Literals.GENERATION_SETTINGS__FILE_EXTENSION = generationSettings_fileExtension;

    // Create headerComment feature
    const generationSettings_headerComment = new BasicEAttribute();
    generationSettings_headerComment.setName('headerComment');
    generationSettings_headerComment.setLowerBound(0);
    generationSettings_headerComment.setUpperBound(1);
    generationSettingsClass.getEStructuralFeatures().push(generationSettings_headerComment);
    GenConfigPackage.Literals.GENERATION_SETTINGS__HEADER_COMMENT = generationSettings_headerComment;

    // Create annotationsPackage feature
    const generationSettings_annotationsPackage = new BasicEAttribute();
    generationSettings_annotationsPackage.setName('annotationsPackage');
    generationSettings_annotationsPackage.setLowerBound(0);
    generationSettings_annotationsPackage.setUpperBound(1);
    generationSettingsClass.getEStructuralFeatures().push(generationSettings_annotationsPackage);
    GenConfigPackage.Literals.GENERATION_SETTINGS__ANNOTATIONS_PACKAGE = generationSettings_annotationsPackage;

    // Create PackageSettings class
    const packageSettingsClass = new BasicEClass();
    packageSettingsClass.setName('PackageSettings');
    packageSettingsClass.setAbstract(false);
    packageSettingsClass.setInterface(false);
    this.getEClassifiers().push(packageSettingsClass);
    packageSettingsClass.setEPackage(this);
    GenConfigPackage.Literals.PACKAGE_SETTINGS = packageSettingsClass;

    // Create prefix feature
    const packageSettings_prefix = new BasicEAttribute();
    packageSettings_prefix.setName('prefix');
    packageSettings_prefix.setLowerBound(1);
    packageSettings_prefix.setUpperBound(1);
    packageSettingsClass.getEStructuralFeatures().push(packageSettings_prefix);
    GenConfigPackage.Literals.PACKAGE_SETTINGS__PREFIX = packageSettings_prefix;

    // Create basePackage feature
    const packageSettings_basePackage = new BasicEAttribute();
    packageSettings_basePackage.setName('basePackage');
    packageSettings_basePackage.setLowerBound(0);
    packageSettings_basePackage.setUpperBound(1);
    packageSettingsClass.getEStructuralFeatures().push(packageSettings_basePackage);
    GenConfigPackage.Literals.PACKAGE_SETTINGS__BASE_PACKAGE = packageSettings_basePackage;

    // Create generateFactory feature
    const packageSettings_generateFactory = new BasicEAttribute();
    packageSettings_generateFactory.setName('generateFactory');
    packageSettings_generateFactory.setLowerBound(0);
    packageSettings_generateFactory.setUpperBound(1);
    packageSettingsClass.getEStructuralFeatures().push(packageSettings_generateFactory);
    GenConfigPackage.Literals.PACKAGE_SETTINGS__GENERATE_FACTORY = packageSettings_generateFactory;

    // Create generatePackage feature
    const packageSettings_generatePackage = new BasicEAttribute();
    packageSettings_generatePackage.setName('generatePackage');
    packageSettings_generatePackage.setLowerBound(0);
    packageSettings_generatePackage.setUpperBound(1);
    packageSettingsClass.getEStructuralFeatures().push(packageSettings_generatePackage);
    GenConfigPackage.Literals.PACKAGE_SETTINGS__GENERATE_PACKAGE = packageSettings_generatePackage;

    // Create generateIndex feature
    const packageSettings_generateIndex = new BasicEAttribute();
    packageSettings_generateIndex.setName('generateIndex');
    packageSettings_generateIndex.setLowerBound(0);
    packageSettings_generateIndex.setUpperBound(1);
    packageSettingsClass.getEStructuralFeatures().push(packageSettings_generateIndex);
    GenConfigPackage.Literals.PACKAGE_SETTINGS__GENERATE_INDEX = packageSettings_generateIndex;

    // Create ClassDefaults class
    const classDefaultsClass = new BasicEClass();
    classDefaultsClass.setName('ClassDefaults');
    classDefaultsClass.setAbstract(false);
    classDefaultsClass.setInterface(false);
    this.getEClassifiers().push(classDefaultsClass);
    classDefaultsClass.setEPackage(this);
    GenConfigPackage.Literals.CLASS_DEFAULTS = classDefaultsClass;

    // Create generateInterface feature
    const classDefaults_generateInterface = new BasicEAttribute();
    classDefaults_generateInterface.setName('generateInterface');
    classDefaults_generateInterface.setLowerBound(0);
    classDefaults_generateInterface.setUpperBound(1);
    classDefaultsClass.getEStructuralFeatures().push(classDefaults_generateInterface);
    GenConfigPackage.Literals.CLASS_DEFAULTS__GENERATE_INTERFACE = classDefaults_generateInterface;

    // Create generateImpl feature
    const classDefaults_generateImpl = new BasicEAttribute();
    classDefaults_generateImpl.setName('generateImpl');
    classDefaults_generateImpl.setLowerBound(0);
    classDefaults_generateImpl.setUpperBound(1);
    classDefaultsClass.getEStructuralFeatures().push(classDefaults_generateImpl);
    GenConfigPackage.Literals.CLASS_DEFAULTS__GENERATE_IMPL = classDefaults_generateImpl;

    // Create rootExtendsClass feature
    const classDefaults_rootExtendsClass = new BasicEAttribute();
    classDefaults_rootExtendsClass.setName('rootExtendsClass');
    classDefaults_rootExtendsClass.setLowerBound(0);
    classDefaults_rootExtendsClass.setUpperBound(1);
    classDefaultsClass.getEStructuralFeatures().push(classDefaults_rootExtendsClass);
    GenConfigPackage.Literals.CLASS_DEFAULTS__ROOT_EXTENDS_CLASS = classDefaults_rootExtendsClass;

    // Create rootExtendsInterface feature
    const classDefaults_rootExtendsInterface = new BasicEAttribute();
    classDefaults_rootExtendsInterface.setName('rootExtendsInterface');
    classDefaults_rootExtendsInterface.setLowerBound(0);
    classDefaults_rootExtendsInterface.setUpperBound(1);
    classDefaultsClass.getEStructuralFeatures().push(classDefaults_rootExtendsInterface);
    GenConfigPackage.Literals.CLASS_DEFAULTS__ROOT_EXTENDS_INTERFACE = classDefaults_rootExtendsInterface;

    // Create FeatureDefaults class
    const featureDefaultsClass = new BasicEClass();
    featureDefaultsClass.setName('FeatureDefaults');
    featureDefaultsClass.setAbstract(false);
    featureDefaultsClass.setInterface(false);
    this.getEClassifiers().push(featureDefaultsClass);
    featureDefaultsClass.setEPackage(this);
    GenConfigPackage.Literals.FEATURE_DEFAULTS = featureDefaultsClass;

    // Create notify feature
    const featureDefaults_notify = new BasicEAttribute();
    featureDefaults_notify.setName('notify');
    featureDefaults_notify.setLowerBound(0);
    featureDefaults_notify.setUpperBound(1);
    featureDefaultsClass.getEStructuralFeatures().push(featureDefaults_notify);
    GenConfigPackage.Literals.FEATURE_DEFAULTS__NOTIFY = featureDefaults_notify;

    // Create property feature
    const featureDefaults_property = new BasicEAttribute();
    featureDefaults_property.setName('property');
    featureDefaults_property.setLowerBound(0);
    featureDefaults_property.setUpperBound(1);
    featureDefaultsClass.getEStructuralFeatures().push(featureDefaults_property);
    GenConfigPackage.Literals.FEATURE_DEFAULTS__PROPERTY = featureDefaults_property;

    // Create ClassOverride class
    const classOverrideClass = new BasicEClass();
    classOverrideClass.setName('ClassOverride');
    classOverrideClass.setAbstract(false);
    classOverrideClass.setInterface(false);
    this.getEClassifiers().push(classOverrideClass);
    classOverrideClass.setEPackage(this);
    GenConfigPackage.Literals.CLASS_OVERRIDE = classOverrideClass;

    // Create ecoreClass feature
    const classOverride_ecoreClass = new BasicEReference();
    classOverride_ecoreClass.setContainment(false);
    classOverride_ecoreClass.setName('ecoreClass');
    classOverride_ecoreClass.setLowerBound(1);
    classOverride_ecoreClass.setUpperBound(1);
    classOverrideClass.getEStructuralFeatures().push(classOverride_ecoreClass);
    GenConfigPackage.Literals.CLASS_OVERRIDE__ECORE_CLASS = classOverride_ecoreClass;

    // Create generateInterface feature
    const classOverride_generateInterface = new BasicEAttribute();
    classOverride_generateInterface.setName('generateInterface');
    classOverride_generateInterface.setLowerBound(0);
    classOverride_generateInterface.setUpperBound(1);
    classOverrideClass.getEStructuralFeatures().push(classOverride_generateInterface);
    GenConfigPackage.Literals.CLASS_OVERRIDE__GENERATE_INTERFACE = classOverride_generateInterface;

    // Create generateImpl feature
    const classOverride_generateImpl = new BasicEAttribute();
    classOverride_generateImpl.setName('generateImpl');
    classOverride_generateImpl.setLowerBound(0);
    classOverride_generateImpl.setUpperBound(1);
    classOverrideClass.getEStructuralFeatures().push(classOverride_generateImpl);
    GenConfigPackage.Literals.CLASS_OVERRIDE__GENERATE_IMPL = classOverride_generateImpl;

    // Create extendsClass feature
    const classOverride_extendsClass = new BasicEAttribute();
    classOverride_extendsClass.setName('extendsClass');
    classOverride_extendsClass.setLowerBound(0);
    classOverride_extendsClass.setUpperBound(1);
    classOverrideClass.getEStructuralFeatures().push(classOverride_extendsClass);
    GenConfigPackage.Literals.CLASS_OVERRIDE__EXTENDS_CLASS = classOverride_extendsClass;

    // Create implementsInterfaces feature
    const classOverride_implementsInterfaces = new BasicEAttribute();
    classOverride_implementsInterfaces.setName('implementsInterfaces');
    classOverride_implementsInterfaces.setLowerBound(0);
    classOverride_implementsInterfaces.setUpperBound(-1);
    classOverrideClass.getEStructuralFeatures().push(classOverride_implementsInterfaces);
    GenConfigPackage.Literals.CLASS_OVERRIDE__IMPLEMENTS_INTERFACES = classOverride_implementsInterfaces;

    // Create featureOverrides feature
    const classOverride_featureOverrides = new BasicEReference();
    classOverride_featureOverrides.setContainment(true);
    classOverride_featureOverrides.setName('featureOverrides');
    classOverride_featureOverrides.setLowerBound(0);
    classOverride_featureOverrides.setUpperBound(-1);
    classOverrideClass.getEStructuralFeatures().push(classOverride_featureOverrides);
    GenConfigPackage.Literals.CLASS_OVERRIDE__FEATURE_OVERRIDES = classOverride_featureOverrides;

    // Create FeatureOverride class
    const featureOverrideClass = new BasicEClass();
    featureOverrideClass.setName('FeatureOverride');
    featureOverrideClass.setAbstract(false);
    featureOverrideClass.setInterface(false);
    this.getEClassifiers().push(featureOverrideClass);
    featureOverrideClass.setEPackage(this);
    GenConfigPackage.Literals.FEATURE_OVERRIDE = featureOverrideClass;

    // Create ecoreFeature feature
    const featureOverride_ecoreFeature = new BasicEReference();
    featureOverride_ecoreFeature.setContainment(false);
    featureOverride_ecoreFeature.setName('ecoreFeature');
    featureOverride_ecoreFeature.setLowerBound(1);
    featureOverride_ecoreFeature.setUpperBound(1);
    featureOverrideClass.getEStructuralFeatures().push(featureOverride_ecoreFeature);
    GenConfigPackage.Literals.FEATURE_OVERRIDE__ECORE_FEATURE = featureOverride_ecoreFeature;

    // Create notify feature
    const featureOverride_notify = new BasicEAttribute();
    featureOverride_notify.setName('notify');
    featureOverride_notify.setLowerBound(0);
    featureOverride_notify.setUpperBound(1);
    featureOverrideClass.getEStructuralFeatures().push(featureOverride_notify);
    GenConfigPackage.Literals.FEATURE_OVERRIDE__NOTIFY = featureOverride_notify;

    // Create property feature
    const featureOverride_property = new BasicEAttribute();
    featureOverride_property.setName('property');
    featureOverride_property.setLowerBound(0);
    featureOverride_property.setUpperBound(1);
    featureOverrideClass.getEStructuralFeatures().push(featureOverride_property);
    GenConfigPackage.Literals.FEATURE_OVERRIDE__PROPERTY = featureOverride_property;

    // Create customGetter feature
    const featureOverride_customGetter = new BasicEAttribute();
    featureOverride_customGetter.setName('customGetter');
    featureOverride_customGetter.setLowerBound(0);
    featureOverride_customGetter.setUpperBound(1);
    featureOverrideClass.getEStructuralFeatures().push(featureOverride_customGetter);
    GenConfigPackage.Literals.FEATURE_OVERRIDE__CUSTOM_GETTER = featureOverride_customGetter;

    // Create customSetter feature
    const featureOverride_customSetter = new BasicEAttribute();
    featureOverride_customSetter.setName('customSetter');
    featureOverride_customSetter.setLowerBound(0);
    featureOverride_customSetter.setUpperBound(1);
    featureOverrideClass.getEStructuralFeatures().push(featureOverride_customSetter);
    GenConfigPackage.Literals.FEATURE_OVERRIDE__CUSTOM_SETTER = featureOverride_customSetter;


    // ============================================
    // Set ESuperTypes (must be done after all classes are created)
    // ============================================

    // ============================================
    // Set ETypes for EReferences (must be done after all classes are created)
    // ============================================
    (GenConfigPackage.Literals.GEN_CONFIG__ECORE_PACKAGE as BasicEReference).setEType(getEcorePackage().getEClassifier('EPackage')!);
    (GenConfigPackage.Literals.GEN_CONFIG__GENERATION as BasicEReference).setEType(GenConfigPackage.Literals.GENERATION_SETTINGS);
    (GenConfigPackage.Literals.GEN_CONFIG__PACKAGE as BasicEReference).setEType(GenConfigPackage.Literals.PACKAGE_SETTINGS);
    (GenConfigPackage.Literals.GEN_CONFIG__CLASS_DEFAULTS as BasicEReference).setEType(GenConfigPackage.Literals.CLASS_DEFAULTS);
    (GenConfigPackage.Literals.GEN_CONFIG__FEATURE_DEFAULTS as BasicEReference).setEType(GenConfigPackage.Literals.FEATURE_DEFAULTS);
    (GenConfigPackage.Literals.GEN_CONFIG__CLASS_OVERRIDES as BasicEReference).setEType(GenConfigPackage.Literals.CLASS_OVERRIDE);
    (GenConfigPackage.Literals.GEN_CONFIG__REFERENCED_PACKAGES as BasicEReference).setEType(GenConfigPackage.Literals.REFERENCED_PACKAGE);
    (GenConfigPackage.Literals.CLASS_OVERRIDE__ECORE_CLASS as BasicEReference).setEType(getEcorePackage().getEClassifier('EClass')!);
    (GenConfigPackage.Literals.CLASS_OVERRIDE__FEATURE_OVERRIDES as BasicEReference).setEType(GenConfigPackage.Literals.FEATURE_OVERRIDE);
    (GenConfigPackage.Literals.FEATURE_OVERRIDE__ECORE_FEATURE as BasicEReference).setEType(getEcorePackage().getEClassifier('EStructuralFeature')!);

    // ============================================
    // Register XML name mappings from ExtendedMetaData annotations
    // ============================================
  }
}
