/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEFactory } from '@emfts/core';
import type { EClass, EObject } from '@emfts/core';
import { GenConfigPackage } from './GenConfigPackage.js';
import type { GenConfig } from './GenConfig.js';
import { GenConfigImpl } from './GenConfigImpl.js';
import type { ReferencedPackage } from './ReferencedPackage.js';
import { ReferencedPackageImpl } from './ReferencedPackageImpl.js';
import type { GenerationSettings } from './GenerationSettings.js';
import { GenerationSettingsImpl } from './GenerationSettingsImpl.js';
import type { PackageSettings } from './PackageSettings.js';
import { PackageSettingsImpl } from './PackageSettingsImpl.js';
import type { ClassDefaults } from './ClassDefaults.js';
import { ClassDefaultsImpl } from './ClassDefaultsImpl.js';
import type { FeatureDefaults } from './FeatureDefaults.js';
import { FeatureDefaultsImpl } from './FeatureDefaultsImpl.js';
import type { ClassOverride } from './ClassOverride.js';
import { ClassOverrideImpl } from './ClassOverrideImpl.js';
import type { FeatureOverride } from './FeatureOverride.js';
import { FeatureOverrideImpl } from './FeatureOverrideImpl.js';

/**
 * Factory for creating GenConfig model objects
 * @generated
 */
export class GenConfigFactory extends BasicEFactory {
  // Lazy singleton instance
  private static _instance: GenConfigFactory;

  static get eINSTANCE(): GenConfigFactory {
    if (!this._instance) {
      this._instance = new GenConfigFactory();
    }
    return this._instance;
  }

  private constructor() {
    super();
    this.setEPackage(GenConfigPackage.eINSTANCE);
  }

  /**
   * Create a new GenConfig instance
   */
  createGenConfig(): GenConfig {
    return new GenConfigImpl();
  }

  /**
   * Create a new ReferencedPackage instance
   */
  createReferencedPackage(): ReferencedPackage {
    return new ReferencedPackageImpl();
  }

  /**
   * Create a new GenerationSettings instance
   */
  createGenerationSettings(): GenerationSettings {
    return new GenerationSettingsImpl();
  }

  /**
   * Create a new PackageSettings instance
   */
  createPackageSettings(): PackageSettings {
    return new PackageSettingsImpl();
  }

  /**
   * Create a new ClassDefaults instance
   */
  createClassDefaults(): ClassDefaults {
    return new ClassDefaultsImpl();
  }

  /**
   * Create a new FeatureDefaults instance
   */
  createFeatureDefaults(): FeatureDefaults {
    return new FeatureDefaultsImpl();
  }

  /**
   * Create a new ClassOverride instance
   */
  createClassOverride(): ClassOverride {
    return new ClassOverrideImpl();
  }

  /**
   * Create a new FeatureOverride instance
   */
  createFeatureOverride(): FeatureOverride {
    return new FeatureOverrideImpl();
  }

  /**
   * Create an instance of the given class
   */
  override create(eClass: EClass): EObject {
    switch (eClass.getName()) {
      case 'GenConfig':
        return this.createGenConfig();
      case 'ReferencedPackage':
        return this.createReferencedPackage();
      case 'GenerationSettings':
        return this.createGenerationSettings();
      case 'PackageSettings':
        return this.createPackageSettings();
      case 'ClassDefaults':
        return this.createClassDefaults();
      case 'FeatureDefaults':
        return this.createFeatureDefaults();
      case 'ClassOverride':
        return this.createClassOverride();
      case 'FeatureOverride':
        return this.createFeatureOverride();
      default:
        throw new Error(`Unknown class: ${eClass.getName()}`);
    }
  }
}
