/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference, EPackage } from '@emfts/core';
import type { GenerationSettings } from './GenerationSettings.js';
import type { PackageSettings } from './PackageSettings.js';
import type { ClassDefaults } from './ClassDefaults.js';
import type { FeatureDefaults } from './FeatureDefaults.js';
import type { ClassOverride } from './ClassOverride.js';
import type { ReferencedPackage } from './ReferencedPackage.js';
import type { GenConfig } from './GenConfig.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of GenConfig
 * @generated
 */
export class GenConfigImpl extends BasicEObject implements GenConfig {
  // Feature ID Constants (eLiterals)
  static readonly ECORE_PACKAGE: number = 0;
  static readonly GENERATION: number = 1;
  static readonly PACKAGE: number = 2;
  static readonly CLASS_DEFAULTS: number = 3;
  static readonly FEATURE_DEFAULTS: number = 4;
  static readonly CLASS_OVERRIDES: number = 5;
  static readonly REFERENCED_PACKAGES: number = 6;

  // Private fields
  private _ecorePackage?: EPackage;
  private _generation?: GenerationSettings;
  private _package?: PackageSettings;
  private _classDefaults?: ClassDefaults;
  private _featureDefaults?: FeatureDefaults;
  private _classOverrides!: EList<ClassOverride>;
  private _referencedPackages!: EList<ReferencedPackage>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.GEN_CONFIG;
  }

  // Getters and Setters
  get ecorePackage(): EPackage {
    return this._ecorePackage!;
  }

  set ecorePackage(value: EPackage) {
    const oldValue = this._ecorePackage;
    this._ecorePackage = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenConfigImpl.ECORE_PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenConfigImpl.ECORE_PACKAGE,
        merge: () => false
      });
    }
  }

  get generation(): GenerationSettings {
    return this._generation!;
  }

  set generation(value: GenerationSettings) {
    const oldValue = this._generation;
    this._generation = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenConfigImpl.GENERATION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenConfigImpl.GENERATION,
        merge: () => false
      });
    }
  }

  get package(): PackageSettings {
    return this._package!;
  }

  set package(value: PackageSettings) {
    const oldValue = this._package;
    this._package = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenConfigImpl.PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenConfigImpl.PACKAGE,
        merge: () => false
      });
    }
  }

  get classDefaults(): ClassDefaults {
    return this._classDefaults!;
  }

  set classDefaults(value: ClassDefaults) {
    const oldValue = this._classDefaults;
    this._classDefaults = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenConfigImpl.CLASS_DEFAULTS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenConfigImpl.CLASS_DEFAULTS,
        merge: () => false
      });
    }
  }

  get featureDefaults(): FeatureDefaults {
    return this._featureDefaults!;
  }

  set featureDefaults(value: FeatureDefaults) {
    const oldValue = this._featureDefaults;
    this._featureDefaults = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenConfigImpl.FEATURE_DEFAULTS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenConfigImpl.FEATURE_DEFAULTS,
        merge: () => false
      });
    }
  }

  get classOverrides(): EList<ClassOverride> {
    if (!this._classOverrides) {
      this._classOverrides = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('classOverrides') as EReference);
    }
    return this._classOverrides;
  }

  get referencedPackages(): EList<ReferencedPackage> {
    if (!this._referencedPackages) {
      this._referencedPackages = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('referencedPackages') as EReference);
    }
    return this._referencedPackages;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenConfigImpl.ECORE_PACKAGE:
        return this.ecorePackage;
      case GenConfigImpl.GENERATION:
        return this.generation;
      case GenConfigImpl.PACKAGE:
        return this.package;
      case GenConfigImpl.CLASS_DEFAULTS:
        return this.classDefaults;
      case GenConfigImpl.FEATURE_DEFAULTS:
        return this.featureDefaults;
      case GenConfigImpl.CLASS_OVERRIDES:
        return this.classOverrides;
      case GenConfigImpl.REFERENCED_PACKAGES:
        return this.referencedPackages;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenConfigImpl.ECORE_PACKAGE:
        this.ecorePackage = newValue as EPackage;
        super.eSet(feature, newValue);
        break;
      case GenConfigImpl.GENERATION:
        this.generation = newValue as GenerationSettings;
        super.eSet(feature, newValue);
        break;
      case GenConfigImpl.PACKAGE:
        this.package = newValue as PackageSettings;
        super.eSet(feature, newValue);
        break;
      case GenConfigImpl.CLASS_DEFAULTS:
        this.classDefaults = newValue as ClassDefaults;
        super.eSet(feature, newValue);
        break;
      case GenConfigImpl.FEATURE_DEFAULTS:
        this.featureDefaults = newValue as FeatureDefaults;
        super.eSet(feature, newValue);
        break;
      case GenConfigImpl.CLASS_OVERRIDES:
        this.classOverrides.clear();
        this.classOverrides.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case GenConfigImpl.REFERENCED_PACKAGES:
        this.referencedPackages.clear();
        this.referencedPackages.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenConfigImpl.ECORE_PACKAGE:
        return this._ecorePackage !== undefined;
      case GenConfigImpl.GENERATION:
        return this._generation !== undefined;
      case GenConfigImpl.PACKAGE:
        return this._package !== undefined;
      case GenConfigImpl.CLASS_DEFAULTS:
        return this._classDefaults !== undefined;
      case GenConfigImpl.FEATURE_DEFAULTS:
        return this._featureDefaults !== undefined;
      case GenConfigImpl.CLASS_OVERRIDES:
        return this._classOverrides !== undefined && !this._classOverrides.isEmpty();
      case GenConfigImpl.REFERENCED_PACKAGES:
        return this._referencedPackages !== undefined && !this._referencedPackages.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenConfigImpl.ECORE_PACKAGE:
        this._ecorePackage = undefined;
        return;
      case GenConfigImpl.GENERATION:
        this._generation = undefined;
        return;
      case GenConfigImpl.PACKAGE:
        this._package = undefined;
        return;
      case GenConfigImpl.CLASS_DEFAULTS:
        this._classDefaults = undefined;
        return;
      case GenConfigImpl.FEATURE_DEFAULTS:
        this._featureDefaults = undefined;
        return;
      case GenConfigImpl.CLASS_OVERRIDES:
        if (this._classOverrides) this._classOverrides.clear();
        return;
      case GenConfigImpl.REFERENCED_PACKAGES:
        if (this._referencedPackages) this._referencedPackages.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
