/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, EPackage, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { GenerationSettings } from './GenerationSettings.js';
import type { PackageSettings } from './PackageSettings.js';
import type { ClassDefaults } from './ClassDefaults.js';
import type { FeatureDefaults } from './FeatureDefaults.js';
import type { ClassOverride } from './ClassOverride.js';
import type { ReferencedPackage } from './ReferencedPackage.js';

/**
 * GenConfig
 * @generated
 */
export interface GenConfig extends EObject {
  ecorePackage: EPackage;
  generation: GenerationSettings;
  package: PackageSettings;
  classDefaults?: ClassDefaults;
  featureDefaults?: FeatureDefaults;
  classOverrides: EList<ClassOverride>;
  referencedPackages: EList<ReferencedPackage>;

}
