/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { GenerationMode } from './GenerationMode.js';

/**
 * GenerationSettings
 * @generated
 */
export interface GenerationSettings extends EObject {
  mode: GenerationMode;
  outputDir: string;
  fileExtension?: string;
  headerComment?: string;
  annotationsPackage?: string;

}
