/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * GenerationSettings
 * @generated
 */
export interface GenerationSettings extends EObject {
  mode: unknown;
  outputDir: unknown;
  fileExtension?: unknown;
  headerComment?: unknown;

}
