/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * GenerationMode
 * @generated
 */
export const GenerationMode = {
  emf: 'emf',
  decorator: 'decorator',
  plain: 'plain'
} as const;

export type GenerationMode = typeof GenerationMode[keyof typeof GenerationMode];

/**
 * Get enum value by name
 */
export function getGenerationMode(name: string): GenerationMode | undefined {
  return (GenerationMode as Record<string, string>)[name] as GenerationMode | undefined;
}

/**
 * Get enum value by literal
 */
export function getGenerationModeByLiteral(literal: string): GenerationMode | undefined {
  if (literal === 'emf') return GenerationMode.emf;
  if (literal === 'decorator') return GenerationMode.decorator;
  if (literal === 'plain') return GenerationMode.plain;
  return undefined;
}
