/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import { GenerationMode } from './GenerationMode.js';
import type { GenerationSettings } from './GenerationSettings.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of GenerationSettings
 * @generated
 */
export class GenerationSettingsImpl extends BasicEObject implements GenerationSettings {
  // Feature ID Constants (eLiterals)
  static readonly MODE: number = 0;
  static readonly OUTPUT_DIR: number = 1;
  static readonly FILE_EXTENSION: number = 2;
  static readonly HEADER_COMMENT: number = 3;
  static readonly ANNOTATIONS_PACKAGE: number = 4;

  // Private fields
  private _mode: GenerationMode = GenerationMode.emf;
  private _outputDir: string = "./generated";
  private _fileExtension: string = ".ts";
  private _headerComment?: string;
  private _annotationsPackage?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.GENERATION_SETTINGS;
  }

  // Getters and Setters
  get mode(): GenerationMode {
    return this._mode!;
  }

  set mode(value: GenerationMode) {
    const oldValue = this._mode;
    this._mode = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenerationSettingsImpl.MODE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenerationSettingsImpl.MODE,
        merge: () => false
      });
    }
  }

  get outputDir(): string {
    return this._outputDir!;
  }

  set outputDir(value: string) {
    const oldValue = this._outputDir;
    this._outputDir = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenerationSettingsImpl.OUTPUT_DIR),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenerationSettingsImpl.OUTPUT_DIR,
        merge: () => false
      });
    }
  }

  get fileExtension(): string {
    return this._fileExtension!;
  }

  set fileExtension(value: string) {
    const oldValue = this._fileExtension;
    this._fileExtension = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenerationSettingsImpl.FILE_EXTENSION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenerationSettingsImpl.FILE_EXTENSION,
        merge: () => false
      });
    }
  }

  get headerComment(): string {
    return this._headerComment!;
  }

  set headerComment(value: string) {
    const oldValue = this._headerComment;
    this._headerComment = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenerationSettingsImpl.HEADER_COMMENT),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenerationSettingsImpl.HEADER_COMMENT,
        merge: () => false
      });
    }
  }

  get annotationsPackage(): string {
    return this._annotationsPackage!;
  }

  set annotationsPackage(value: string) {
    const oldValue = this._annotationsPackage;
    this._annotationsPackage = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(GenerationSettingsImpl.ANNOTATIONS_PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => GenerationSettingsImpl.ANNOTATIONS_PACKAGE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenerationSettingsImpl.MODE:
        return this.mode;
      case GenerationSettingsImpl.OUTPUT_DIR:
        return this.outputDir;
      case GenerationSettingsImpl.FILE_EXTENSION:
        return this.fileExtension;
      case GenerationSettingsImpl.HEADER_COMMENT:
        return this.headerComment;
      case GenerationSettingsImpl.ANNOTATIONS_PACKAGE:
        return this.annotationsPackage;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenerationSettingsImpl.MODE:
        this.mode = newValue as GenerationMode;
        super.eSet(feature, newValue);
        break;
      case GenerationSettingsImpl.OUTPUT_DIR:
        this.outputDir = newValue as string;
        super.eSet(feature, newValue);
        break;
      case GenerationSettingsImpl.FILE_EXTENSION:
        this.fileExtension = newValue as string;
        super.eSet(feature, newValue);
        break;
      case GenerationSettingsImpl.HEADER_COMMENT:
        this.headerComment = newValue as string;
        super.eSet(feature, newValue);
        break;
      case GenerationSettingsImpl.ANNOTATIONS_PACKAGE:
        this.annotationsPackage = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenerationSettingsImpl.MODE:
        return this._mode !== GenerationMode.emf;
      case GenerationSettingsImpl.OUTPUT_DIR:
        return this._outputDir !== "./generated";
      case GenerationSettingsImpl.FILE_EXTENSION:
        return this._fileExtension !== ".ts";
      case GenerationSettingsImpl.HEADER_COMMENT:
        return this._headerComment !== undefined;
      case GenerationSettingsImpl.ANNOTATIONS_PACKAGE:
        return this._annotationsPackage !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case GenerationSettingsImpl.MODE:
        this._mode = GenerationMode.emf;
        return;
      case GenerationSettingsImpl.OUTPUT_DIR:
        this._outputDir = "./generated";
        return;
      case GenerationSettingsImpl.FILE_EXTENSION:
        this._fileExtension = ".ts";
        return;
      case GenerationSettingsImpl.HEADER_COMMENT:
        this._headerComment = undefined;
        return;
      case GenerationSettingsImpl.ANNOTATIONS_PACKAGE:
        this._annotationsPackage = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
