/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

// Package and Factory
export { GenConfigPackage } from './GenConfigPackage.js';
export { GenConfigFactory } from './GenConfigFactory.js';

// Interfaces
export type { GenConfig } from './GenConfig.js';
export type { ReferencedPackage } from './ReferencedPackage.js';
export type { GenerationSettings } from './GenerationSettings.js';
export type { PackageSettings } from './PackageSettings.js';
export type { ClassDefaults } from './ClassDefaults.js';
export type { FeatureDefaults } from './FeatureDefaults.js';
export type { ClassOverride } from './ClassOverride.js';
export type { FeatureOverride } from './FeatureOverride.js';

// Implementations (including abstract classes, as they're extended by subclasses)
export { GenConfigImpl } from './GenConfigImpl.js';
export { ReferencedPackageImpl } from './ReferencedPackageImpl.js';
export { GenerationSettingsImpl } from './GenerationSettingsImpl.js';
export { PackageSettingsImpl } from './PackageSettingsImpl.js';
export { ClassDefaultsImpl } from './ClassDefaultsImpl.js';
export { FeatureDefaultsImpl } from './FeatureDefaultsImpl.js';
export { ClassOverrideImpl } from './ClassOverrideImpl.js';
export { FeatureOverrideImpl } from './FeatureOverrideImpl.js';

// Enums
export { GenerationMode, getGenerationMode, getGenerationModeByLiteral } from './GenerationMode.js';
export { PropertyMode, getPropertyMode, getPropertyModeByLiteral } from './PropertyMode.js';
