/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * PackageSettings
 * @generated
 */
export interface PackageSettings extends EObject {
  prefix: string;
  basePackage?: string;
  generateFactory?: boolean;
  generatePackage?: boolean;
  generateIndex?: boolean;

}
