/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * PackageSettings
 * @generated
 */
export interface PackageSettings extends EObject {
  prefix: unknown;
  basePackage?: unknown;
  generateFactory?: unknown;
  generatePackage?: unknown;
  generateIndex?: unknown;

}
