/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { PackageSettings } from './PackageSettings.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of PackageSettings
 * @generated
 */
export class PackageSettingsImpl extends BasicEObject implements PackageSettings {
  // Feature ID Constants (eLiterals)
  static readonly PREFIX: number = 0;
  static readonly BASE_PACKAGE: number = 1;
  static readonly GENERATE_FACTORY: number = 2;
  static readonly GENERATE_PACKAGE: number = 3;
  static readonly GENERATE_INDEX: number = 4;

  // Private fields
  private _prefix: string = "";
  private _basePackage?: string;
  private _generateFactory: boolean = true;
  private _generatePackage: boolean = true;
  private _generateIndex: boolean = true;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.PACKAGE_SETTINGS;
  }

  // Getters and Setters
  get prefix(): string {
    return this._prefix!;
  }

  set prefix(value: string) {
    const oldValue = this._prefix;
    this._prefix = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageSettingsImpl.PREFIX),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageSettingsImpl.PREFIX,
        merge: () => false
      });
    }
  }

  get basePackage(): string {
    return this._basePackage!;
  }

  set basePackage(value: string) {
    const oldValue = this._basePackage;
    this._basePackage = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageSettingsImpl.BASE_PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageSettingsImpl.BASE_PACKAGE,
        merge: () => false
      });
    }
  }

  get generateFactory(): boolean {
    return this._generateFactory!;
  }

  set generateFactory(value: boolean) {
    const oldValue = this._generateFactory;
    this._generateFactory = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageSettingsImpl.GENERATE_FACTORY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageSettingsImpl.GENERATE_FACTORY,
        merge: () => false
      });
    }
  }

  get generatePackage(): boolean {
    return this._generatePackage!;
  }

  set generatePackage(value: boolean) {
    const oldValue = this._generatePackage;
    this._generatePackage = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageSettingsImpl.GENERATE_PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageSettingsImpl.GENERATE_PACKAGE,
        merge: () => false
      });
    }
  }

  get generateIndex(): boolean {
    return this._generateIndex!;
  }

  set generateIndex(value: boolean) {
    const oldValue = this._generateIndex;
    this._generateIndex = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageSettingsImpl.GENERATE_INDEX),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageSettingsImpl.GENERATE_INDEX,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageSettingsImpl.PREFIX:
        return this.prefix;
      case PackageSettingsImpl.BASE_PACKAGE:
        return this.basePackage;
      case PackageSettingsImpl.GENERATE_FACTORY:
        return this.generateFactory;
      case PackageSettingsImpl.GENERATE_PACKAGE:
        return this.generatePackage;
      case PackageSettingsImpl.GENERATE_INDEX:
        return this.generateIndex;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageSettingsImpl.PREFIX:
        this.prefix = newValue as string;
        super.eSet(feature, newValue);
        break;
      case PackageSettingsImpl.BASE_PACKAGE:
        this.basePackage = newValue as string;
        super.eSet(feature, newValue);
        break;
      case PackageSettingsImpl.GENERATE_FACTORY:
        this.generateFactory = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case PackageSettingsImpl.GENERATE_PACKAGE:
        this.generatePackage = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case PackageSettingsImpl.GENERATE_INDEX:
        this.generateIndex = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageSettingsImpl.PREFIX:
        return this._prefix !== "";
      case PackageSettingsImpl.BASE_PACKAGE:
        return this._basePackage !== undefined;
      case PackageSettingsImpl.GENERATE_FACTORY:
        return this._generateFactory !== true;
      case PackageSettingsImpl.GENERATE_PACKAGE:
        return this._generatePackage !== true;
      case PackageSettingsImpl.GENERATE_INDEX:
        return this._generateIndex !== true;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageSettingsImpl.PREFIX:
        this._prefix = "";
        return;
      case PackageSettingsImpl.BASE_PACKAGE:
        this._basePackage = undefined;
        return;
      case PackageSettingsImpl.GENERATE_FACTORY:
        this._generateFactory = true;
        return;
      case PackageSettingsImpl.GENERATE_PACKAGE:
        this._generatePackage = true;
        return;
      case PackageSettingsImpl.GENERATE_INDEX:
        this._generateIndex = true;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
