/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * PropertyMode
 * @generated
 */
export const PropertyMode = {
  editable: 'editable',
  readonly: 'readonly',
  none: 'none'
} as const;

export type PropertyMode = typeof PropertyMode[keyof typeof PropertyMode];

/**
 * Get enum value by name
 */
export function getPropertyMode(name: string): PropertyMode | undefined {
  return (PropertyMode as Record<string, string>)[name] as PropertyMode | undefined;
}

/**
 * Get enum value by literal
 */
export function getPropertyModeByLiteral(literal: string): PropertyMode | undefined {
  if (literal === 'editable') return PropertyMode.editable;
  if (literal === 'readonly') return PropertyMode.readonly;
  if (literal === 'none') return PropertyMode.none;
  return undefined;
}
