/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * ReferencedPackage
 * @generated
 */
export interface ReferencedPackage extends EObject {
  nsURI: unknown;
  importPath: unknown;

}
