/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ReferencedPackage } from './ReferencedPackage.js';
import { GenConfigPackage } from './GenConfigPackage.js';

/**
 * Implementation of ReferencedPackage
 * @generated
 */
export class ReferencedPackageImpl extends BasicEObject implements ReferencedPackage {
  // Feature ID Constants (eLiterals)
  static readonly NS_U_R_I: number = 0;
  static readonly IMPORT_PATH: number = 1;

  // Private fields
  private _nsURI?: unknown;
  private _importPath?: unknown;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return GenConfigPackage.Literals.REFERENCED_PACKAGE;
  }

  // Getters and Setters
  get nsURI(): unknown {
    return this._nsURI!;
  }

  set nsURI(value: unknown) {
    const oldValue = this._nsURI;
    this._nsURI = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ReferencedPackageImpl.NS_U_R_I),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ReferencedPackageImpl.NS_U_R_I,
        merge: () => false
      });
    }
  }

  get importPath(): unknown {
    return this._importPath!;
  }

  set importPath(value: unknown) {
    const oldValue = this._importPath;
    this._importPath = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ReferencedPackageImpl.IMPORT_PATH),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ReferencedPackageImpl.IMPORT_PATH,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ReferencedPackageImpl.NS_U_R_I:
        return this.nsURI;
      case ReferencedPackageImpl.IMPORT_PATH:
        return this.importPath;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ReferencedPackageImpl.NS_U_R_I:
        this.nsURI = newValue as unknown;
        super.eSet(feature, newValue);
        break;
      case ReferencedPackageImpl.IMPORT_PATH:
        this.importPath = newValue as unknown;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ReferencedPackageImpl.NS_U_R_I:
        return this._nsURI !== undefined;
      case ReferencedPackageImpl.IMPORT_PATH:
        return this._importPath !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ReferencedPackageImpl.NS_U_R_I:
        this._nsURI = undefined;
        return;
      case ReferencedPackageImpl.IMPORT_PATH:
        this._importPath = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
