import type { GenModel } from '../genmodel/GenModel.js';
import type { GenPackage } from '../genmodel/GenPackage.js';
import type { GenClass } from '../genmodel/GenClass.js';
import type { GeneratorOptions } from './GeneratorOptions.js';
import { TypeMapper } from './TypeMapper.js';
import { ImportResolver } from './ImportResolver.js';
import * as EObjectHelper from '../util/EObjectHelper.js';

/**
 * Diagnostic message from generation
 */
export interface Diagnostic {
  level: 'info' | 'warning' | 'error';
  message: string;
  source?: string;
  line?: number;
}

/**
 * Context shared during code generation
 */
export class GeneratorContext {
  readonly genModel: GenModel;
  readonly options: GeneratorOptions;
  readonly typeMapper: TypeMapper;
  readonly importResolver: ImportResolver;
  readonly diagnostics: Diagnostic[] = [];

  private currentPackage: GenPackage | null = null;
  private currentClass: GenClass | null = null;

  constructor(genModel: GenModel, options: GeneratorOptions) {
    this.genModel = genModel;
    this.options = options;
    this.typeMapper = new TypeMapper();
    this.importResolver = new ImportResolver();
  }

  /**
   * Set the current package being processed
   */
  setCurrentPackage(pkg: GenPackage): void {
    this.currentPackage = pkg;
  }

  /**
   * Get the current package being processed
   */
  getCurrentPackage(): GenPackage | null {
    return this.currentPackage;
  }

  /**
   * Set the current class being processed
   */
  setCurrentClass(cls: GenClass): void {
    this.currentClass = cls;
  }

  /**
   * Get the current class being processed
   */
  getCurrentClass(): GenClass | null {
    return this.currentClass;
  }

  /**
   * Add an info diagnostic
   */
  info(message: string, source?: string): void {
    this.diagnostics.push({ level: 'info', message, source });
  }

  /**
   * Add a warning diagnostic
   */
  warn(message: string, source?: string): void {
    this.diagnostics.push({ level: 'warning', message, source });
  }

  /**
   * Add an error diagnostic
   */
  error(message: string, source?: string): void {
    this.diagnostics.push({ level: 'error', message, source });
  }

  /**
   * Check if there are any errors
   */
  hasErrors(): boolean {
    return this.diagnostics.some(d => d.level === 'error');
  }

  /**
   * Get the file header
   */
  getFileHeader(): string {
    if (this.options.fileHeader) {
      return this.options.fileHeader;
    }

    if (this.genModel.copyrightText) {
      return `/*\n * ${this.genModel.copyrightText.split('\n').join('\n * ')}\n */`;
    }

    return `/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */`;
  }

  /**
   * Get indentation string
   */
  getIndent(level: number = 1): string {
    const char = this.options.indentation === 'tabs' ? '\t' : ' '.repeat(this.options.indentSize);
    return char.repeat(level);
  }

  /**
   * Get line ending string
   */
  getLineEnding(): string {
    return this.options.lineEnding === 'crlf' ? '\r\n' : '\n';
  }
}
